### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by mahulchak** [tamuri/treesub#1]
Hi,
how do I install treesub? 
Thanks,
Mahul

**Comment by ekamau** [comment]
Having the same question too;

Can't see the treesub.jar???

**Comment by tamuri** [comment]
Download the source code and then build the source code using [Ant](http://ant.apache.org/) to get the treesub.jar file.

**Comment by IVoorhees** [comment]
Could you please provide some more details for using ANT to build the source code? Not sure how to do that exactly.

**Comment by l-yampolsky** [comment]
same issue - please provide installation instructions. I got and installed ant. Now what?
Thanks in advance!

**Comment by l-yampolsky** [comment]
to answer my own and previous question: once Ant is installed and JAVA_HOME is set it is necessary to type ant inside the treesub-master directory. How many human-hours could have been saved if the authors included this simple instruction into their README?
