### ISSUE TITLE
Error: option C?.

### ISSUE THREAD

**Issue by migrau** [tamuri/treesub#10]
It is a PAML error? Any idea? Thanks.

![treesub_error2](https://user-images.githubusercontent.com/6456499/62842124-106a7d80-bcf3-11e9-999d-9fca0defaf93.png)

**Comment by rjwebby2211** [comment]
I am getting this exact same error leading to the Error: java.lang.NullPointerException issue. I don't have any stop codons in my alignment so I am guessing that it is inferring an ancestral stop codon. Is there anyway around this?

**Comment by migrau** [comment]
@rjwebby2211 at least for me, I think the error was not related to stop codons (like [here](https://groups.google.com/forum/#!searchin/pamlsoftware/stop$20codon|sort:date/pamlsoftware/ltFKSiVBP7E/UNu1iJeKAAAJ)). I asked in the [paml google group](https://groups.google.com/forum/#!topic/pamlsoftware/oM3UgVnBEqM)...

**Comment by JuaninAR** [comment]
I think that for treesub is necessary a matrix with AA not with codons... may be if you are using as input file a datamatrix with codons change to AA the input file could solve the problem...

**Comment by JuaninAR** [comment]
No, treesub works ok with data matrix with bases.  The problem could be if your input file contain sequences with a number of bases not exactly a multiple of 3 (your alignment file seems to have 1636 as sequence length but with this length is not possible to convert to 545 AA or 546 AA in treesub...

**Comment by JuaninAR** [comment]
I think that if your input file contain a data matrix with 1635 positions as sequence length treesub should work!

**Comment by migrau** [comment]
@JuaninAR Many thanks! You were right, trimming the alignment solved the problem. Cheers!
