### ISSUE TITLE
Java 'NullPointerException' error

### ISSUE THREAD

**Issue by ekamau** [tamuri/treesub#2]
How do I solve the error: 'Exception in thread "main" java.lang.NullPointerException
                                                at treesub.ancestral.ParseRST.getSequences(Unknown Source)
                                                at treesub.ancestral.ParseRST.run(Unknown Source)
                                                at treesub.ancestral.ParseRST.main(Unknown Source)'
This is happening at the last step 6/6 - building tree for substitutions.

**Comment by ekamau** [comment]
Note: the other 5 steps seem to run successfully, according to the output on the program console. So what could be going wrong with the last step?

Kindly assist, thanks.

anyone??? any clues?

**Comment by timosong** [comment]
Not sure if you already found the solution, but most likely you had stop codons in your alignment file.  

Remove the codons and the error should disappear.

**Comment by l-yampolsky** [comment]
Dear Colleagues,
I am having the same issue:

```
    NG86: stop codon TAG.

    Successfully ran PAML.

    [6/6] Parsing PAML results and building tree for substitutions.
    ERROR: java.lang.NullPointerException
```

No stop codons in file (in frame), TAG or any other. Checked again and again. Any suggestions of what may cause the script to think that there is a stop?

**Comment by tamuri** [comment]
Can you share the alignment so I can replicate the error?

**Comment by l-yampolsky** [comment]
Thanks! Gladly; tried to, but the file is too large. It’s a bumper-to-bumper concatenate of 976 individual alignments, all codon-based, all multiples of 3, no stops in any.
Concatenated using catfasta2phyml (github.com/nylander/catfasta2phyml). Concatenation should not create a stop by shifting it in-frame, as all individual alignments are in-frame.

please download it from:
https://www.dropbox.com/s/k0bwquo5t3xksko/acantho_gar_976.nostop.fasta?dl=0

Please let me know if there is any problem with the download.

Will very much appreciate your help!

Regards,


--
Lev Yampolsky

Professor
Department of Biological Sciences
East Tennessee State University
Box 70703
Johnson City TN 37614-1710
Cell 423-676-7489
Office/lab 423-439-4359
Fax        423-439-5958

**Comment by tamuri** [comment]
Your alignment is fine but it looks like PAML throws an error when it finds that the most probable reconstructed ancestral state is a stop codon (it's trying to count synonymous & non-synonymous changes).

Unfortunately, out of my hands - I will discuss with Ziheng when I next meet him. In the meantime, I hacked baseml and emailed you the table of results (and the tree, but you have so many non-synonymous changes, it's a bit useless to visualise them on this tree).

**Comment by l-yampolsky** [comment]
Thank you so much!

This is weird, isn’t it? That there are no stops in alignments, but it gets reconstructed. Must be a 2-nucleotide change from Y to W or something like this that PAML does not see happening other than in two parallel changes from the ancestral stop.

Thanks again, I really appreciate.

Lev

**Comment by tamuri** [comment]
Yes, it's site 196615 in the (converted) amino acid alignment:

```
>gam10_1
TCA
>gam10_2
TCG
>gam2
TCG
>gam26_6
TCG
>gam28_1
TGG
>gam3
TCG
>gam31_10
TCG
>gam5
TAC
>gam8
TAC
>gam9_4
TAC
```

**Comment by l-yampolsky** [comment]
Dear Asif,


Once again thank you for your help with treesub. Another of my alignments completed without an error. However, the third one generated the same error, presumably because of an inferred stop codon again. Could you instruct me how did you parse the results to extract the table of substitutions? You said you looked into baseml, but this files seems to contain very little. I can see that all the necessary info is present in rst, but it's not clear how you extract the list of substitutions from there - perhaps you have a scrip that does it.



Here is the link to the folder with the alignment and the results:

https://www.dropbox.com/sh/y5i8jhgysjyts69/AAAwieZKS5x4rgMoVaAp3KQPa?dl=0



Thank you very much in advance for your help!


Lev Yampolsky


________________________________

**Comment by tamuri** [comment]
If it's failing due to the same STOP codon error then baseml exits before it completes and the results are incomplete. The only way to fix this for now is to edit the PAML source code and compile a new version for your computer. Specifically, comment out the `exit(1)` around line 341 line in tools.c like this:

```c
      if (iaa[i] == -1) {
         printf("\nNG86: stop codon %s.\n", getcodon(str, iy[i]));
//exit(-1);
      }
```

Recompile and you should be good to go.

**Comment by l-yampolsky** [comment]
Same result:

[6/6] Parsing PAML results and building tree for substitutions.
ERROR: java.lang.NullPointerException


Maybe I did something wrong compiling? I did, on MacOS10.12, (as described in src/README.txt):


cd ~/[...]/paml4.8/src

make (there was a bunch of warnings)

cp baseml basemlg codeml evolver pamp yn00 mcmctree chi2 ..

rm *.o

rm: *.o: No such file or directory


As the result I have now files with the same names, but much smaller sizes in

paml4.8 and in paml4.8/bin, which does not look right. Prior to this I did not compile PAML, but used precompiled Mac version.


Any ideas of what I may be doing wrong?


________________________________

**Comment by tamuri** [comment]
Make sure that the path to baseml in treesub (second box from the top) is pointing to your new compiled version of baseml (I think paml4.8/baseml).

Otherwise it might well be some other problem. Check whether you can run baseml directly on your files (not through treesub).

**Comment by l-yampolsky** [comment]
one more question if you don't mind.

Why are you using baseml, given that alignments are codon-based? wouldn't codeml be the right component to do the reconstructions?


Thanks!


________________________________

**Comment by tamuri** [comment]
Using baseml nucleotide-based analysis partitioning on codon position is substantially faster than any of the codon models. Also, the large variety of codon models require more configuration/tuning for the data to hand, which is not so amenable to a "one-button" tool like treesub. (Plus usual time constraints etc.)
