### ISSUE TITLE
org.biojava3.core.exceptions.compoundnotfounderror

### ISSUE THREAD

**Issue by noia00** [tamuri/treesub#3]
I keep getting this message after I hit run:
org.biojava3.core.exceptions.compoundnotfounderror 

What might be a solution to this?

**Comment by tamuri** [comment]
Is there any more information in the stack trace? That's an error thrown by BioJava when trying to parse your sequence alignment. Make sure your alignment is a valid FASTA file of protein-coding sequences. You might have a character your sequences that the parser does not understand.

**Comment by jenurfor** [comment]
Hello Tamuri,

Thank you for making this amazing package! However, I've encountered the same issue with noia00. 
Here are some details: 

**The error messages:** 
[1/6] Copying file from '/DATA/Peiyu/PAML_results/H5-17_ancestral_recon/H1_fas/H5_20160623_20170206_17_small_new.phy' to '/DATA/Peiyu/PAML_results/H5-17_ancestral_recon/H1_fas/alignment'.
Successfully copied file.
[2/6] Converting FASTA file 'alignment' to PHYLIP file 'alignment.phylip'.
ERROR: org.biojava3.core.exceptions.CompoundNotFoundError: Compound not found for: Cannot find compound for: 1
Compound not found for: Cannot find compound for: 1

**Paths for RaxML, PAML and alignment:**
/DATA/standard-RAxML-master/raxmlHPC-PTHREADS-SSE3
/DATA/paml4.9d/bin/baseml
/DATA/gen1.phy

I've tried two format of the phylip files, one is well-accepted by PAML CODEML, the other is directly converted from fasta with script Fasta2Phylip.pl and none of them works. Please find attached two phylips and the script I used.

My PAML and RaxML works fine and PAL and BIoJAVA were installed on ubuntu. Not sure why I can't get treesub work. Any help from you will be greatly appreciated. :-)

Best wishes,

Peiyu 


[Fasta2Phylip.pl.txt](https://github.com/tamuri/treesub/files/813807/Fasta2Phylip.pl.txt)
[gen1.txt](https://github.com/tamuri/treesub/files/813790/gen1.txt)
[gen2.txt](https://github.com/tamuri/treesub/files/813789/gen2.txt)

**Comment by tamuri** [comment]
The treesub program works with FASTA format files only. It will convert alignments to Phylip format internally; you should not do it yourself.

**Comment by jenurfor** [comment]
Thank you for your swift reply. I've imported fasta file and got this error message:
RAxML was called as follows:

/DATA/Peiyu/standard-RAxML-master/raxmlHPC-PTHREADS-SSE3 -m GTRGAMMA -T 2 -# 10 -s alignment.raxml.phylip -n RECON 
Partition: 0 with name: No Name Provided
Base frequencies: 0.352 0.178 0.218 0.253 
Error: you need to specify a random number seed with "-p" for the randomized stepwise addition
parsimony algorithm or random tree building algorithm such that runs can be reproduced and debugged ... exiting
raxmlHPC-PTHREADS-SSE3: fastDNAparsimony.c:137: checkSeed: Assertion `adef->parsimonySeed > 0' failed.
Successfully ran RAxML.
[4/6] Rooting tree by outgroup sequence.
ERROR: java.io.FileNotFoundException: /DATA/Peiyu/PAML_results/H5-17_ancestral_recon/H1_fas/RAxML_bestTree.RECON (No such file or directory)

Thank you for your help in advance. :-)

**Comment by tamuri** [comment]
Strange error. It is missing the "-p" option for RAxML. Did you edit the code at all or the annotator.properties file? The annotator.properties file contains the RAxML options used for the program. I think the defaults are "-m GTRGAMMA -T 2 -# 10 -p 12345". Make sure you have the "-p" option.

**Comment by jenurfor** [comment]
Thank you so much Tamuri! Indeed the -p is missing in annotator.properties file and the problem was solved after adding it back. Wonderful package!   :-D
