### ISSUE TITLE
command line version?

### ISSUE THREAD

**Issue by nhassell** [tamuri/treesub#4]
Is there some way that the treesub program could be run through command line without the gui?

**Comment by tamuri** [comment]
If you are comfortable with the command line, you can run RAxML and PAML manually with the appropriate options for ancestral reconstruction. Then you can do this:

> If you already have run PAML analysis, you can run the following to create substitutions.tree and substitutions.tsv files. You need to have run PAML with the appropriate options. For example, if the rst file is in /path/to/paml/results run:
> `java -cp dist/treesub.jar treesub.ancestral.ParseRST /path/to/paml/results`
